### ISSUE TITLE
query string encoding fails with semicolon in the user agent

### ISSUE THREAD

**Issue by wasperen** [dockwa/openpixel#18]
The user agent string includes semicolons. For example: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0."

Formally these semicolons are illegal characters in a query string (see https://www.w3.org/TR/2014/REC-html5-20141028/forms.html#url-encoded-form-data).

This is why the results on my end look funny. Here the query string is parsed as follows (see first two keys)

```
{
  "ua": "Mozilla/5.0 (X11",
  " Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36": "",
  "bn": "Chrome 71",
  "cd": "24",
  "de": "windows-1252",
  "dl": "XXXX",
  "dt": "TESY",
  "ed": "",
  "ev": "pageclose",
  "id": "ID-XXXXXXXX",
  "md": "false",
  "rl": "",
  "sr": "1920x1080",
  "ts": "1550069975865",
  "uid": "HHHHHHH",
  "utm_campaign": "",
  "utm_content": "",
  "utm_medium": "",
  "utm_source": "",
  "utm_term": "",
  "v": "1",
  "vp": "1918x959"
}
```

**Comment by stuyam** [comment]
You are right! 
Currently we use `encodeURI()` for the whole url, but that skips things like `&` because it assumes it is part of the url, but it also seems to skip `;`'s.

Here is a screenshot of a test I did.
<img width="369" alt="screenshot 2019-02-13 12 47 22" src="https://user-images.githubusercontent.com/1553779/52732185-92205f00-2f8d-11e9-9346-d1691bcd3bff.png">

So It looks like `encodedURIComponent()` is what we want to use and encoded each item individually before joining.
